### PR TITLE
Aydin's changes to the repo

### PR DESCRIPTION
**Pull request by Aydin62**
Hi. My Telegram profile is:  AydinManz
Aydin Manzouri

### CODE REVIEW

**Review by ProgramCrafter — APPROVED** [review]
Thank you for contribution! I'll merge once I check whether everything works.

**Comment by ProgramCrafter** [comment]
It crashed with the following error message:
```
totp-uefi>cargo +nightly build --target x86_64-unknown-uefi -r
    Updating crates.io index
warning: Patch `base32 v1.0.0-patch-nostd-pc (D:\Rust\totp-uefi\base32-1.0.0-patch-nostd-pc)` was not used in the crate graph.
Patch `sha1 v1.0.0-patch-nostd-pc (D:\Rust\totp-uefi\sha1-1.0.0-patch-nostd-pc)` was not used in the crate graph.
Patch `sha2 v1.0.0-patch-nostd-pc (D:\Rust\totp-uefi\sha2-1.0.0-patch-nostd-pc)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
  Downloaded proc-macro2 v1.0.69
  Downloaded num-traits v0.2.17
  Downloaded uguid v2.1.0
  Downloaded 3 crates (107.6 KB) in 1.70s
   Compiling proc-macro2 v1.0.69
   Compiling num-traits v0.2.17
   Compiling uguid v2.1.0
   Compiling base32 v0.4.0
   Compiling crypto-common v0.1.6
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-uefi` target may not support the standard library
  = note: `std` is required by `base32` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\crypto-common-0.1.6\src\lib.rs:13:1
   |
13 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `x86_64-unknown-uefi` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: cannot find attribute `derive` in this scope
 --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:8:3
  |
8 | #[derive(Copy,Clone)]
  |   ^^^^^^

error[E0408]: variable `None` is not bound in all patterns
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:83:21
   |
83 |                     Some(&-1) | None => return None,
   |                     ^^^^^^^^^   ---- variable not in all patterns
   |                     |
   |                     pattern doesn't bind `None`
   |
help: if you meant to match on a variant or a `const` item, consider making the path in the pattern qualified: `path::to::ModOrType::None`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:83:33
   |
83 |                     Some(&-1) | None => return None,
   |                                 ^^^^

error[E0412]: cannot find type `String` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:17:51
   |
17 | pub fn encode(alphabet: Alphabet, data: &[u8]) -> String {
   |                                                   ^^^^^^ not found in this scope

error[E0412]: cannot find type `Option` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:60:50
   |
60 | pub fn decode(alphabet: Alphabet, data: &str) -> Option<Vec<u8>> {
   |                                                  ^^^^^^ not found in this scope

error[E0412]: cannot find type `Vec` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:60:57
   |
60 | pub fn decode(alphabet: Alphabet, data: &str) -> Option<Vec<u8>> {
   |                                                         ^^^ not found in this scope

error[E0425]: cannot find value `None` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:62:16
   |
62 |         return None;
   |                ^^^^ not found in this scope

error[E0531]: cannot find tuple struct or tuple variant `Some` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:83:21
   |
83 |                     Some(&-1) | None => return None,
   |                     ^^^^ not found in this scope

error[E0531]: cannot find tuple struct or tuple variant `Some` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:84:21
   |
84 |                     Some(&value) => buf[i] = value as u8,
   |                     ^^^^ not found in this scope

error[E0433]: failed to resolve: use of undeclared type `Vec`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:22:19
   |
22 |     let mut ret = Vec::with_capacity((data.len()+3)/4*5);
   |                   ^^^ use of undeclared type `Vec`

error: could not compile `crypto-common` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `enumerate` found for struct `core::slice::Iter` in the current scope
    --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:27:41
     |
27   |             for (i, &b) in chunk.iter().enumerate() {
     |                                         ^^^^^^^^^ method not found in `Iter<'_, u8>`
     |
    ::: C:\Users\***\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\iter\traits\iterator.rs:1016:8
     |
1016 |     fn enumerate(self) -> Enumerate<Self>
     |        --------- the method is available for `core::slice::Iter<'_, u8>` here
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
1    + use core::iter::Iterator;
     |

error[E0433]: failed to resolve: use of undeclared type `String`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:54:5
   |
54 |     String::from_utf8(ret).unwrap()
   |     ^^^^^^ use of undeclared type `String`

error[E0433]: failed to resolve: use of undeclared type `Vec`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:77:19
   |
77 |     let mut ret = Vec::with_capacity((output_length+4)/5*5);
   |                   ^^^ use of undeclared type `Vec`

error[E0599]: no method named `enumerate` found for struct `core::slice::Iter` in the current scope
    --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:81:41
     |
81   |             for (i, &c) in chunk.iter().enumerate() {
     |                                         ^^^^^^^^^ method not found in `Iter<'_, u8>`
     |
    ::: C:\Users\***\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\iter\traits\iterator.rs:1016:8
     |
1016 |     fn enumerate(self) -> Enumerate<Self>
     |        --------- the method is available for `core::slice::Iter<'_, u8>` here
     |
     = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
     |
1    + use core::iter::Iterator;
     |

error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\base32-0.4.0\src\lib.rs:96:5
   |
96 |     Some(ret)
   |     ^^^^ not found in this scope

Some errors have detailed explanations: E0408, E0412, E0425, E0433, E0463, E0531, E0599.
For more information about an error, try `rustc --explain E0408`.
error: could not compile `base32` (lib) due to 15 previous errors
```

**Review by ProgramCrafter — CHANGES_REQUESTED** [review]
Checking out repository and compiling didn't work, unfortunately.

**Comment by Aydin62** [comment]
As I remember, I did the job in accordance with your answers to my questions. Can't figure out the error. Could it be, for example, due to the deletion of ```crypto-commons``` as you had allowed before?

**Comment by Aydin62** [comment]
The first line of ```build.bat``` reads:

```cargo +nightly build --target x86_64-unknown-uefi -r```

**Comment by Aydin62** [comment]
Can't figure out the main cause. As I remember, I did the job in accordance with your answers to my questions. Could it be, for example, due to the removal of ```crypto-common``` as you had allowed? Esp., I see the following piece of log in the above output:

```error[E0463]: can't find crate for `std`
  --> C:\Users\***\.cargo\registry\src\index.crates.io-6f17d22bba15001f\crypto-common-0.1.6\src\lib.rs:13:1```

Here, it refers to ```crypto-common```, which is absent in my repository, of course.

**Pull request closed without merging**
